Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _272ass.Data;
using _272ass.Models;

namespace _272ass.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        
        private _272assContext db = new _272assContext();

        // GET: Events
        [Authorize(Roles ="Organiser, Admin")]
        public ActionResult Index()
        {
            var events = db.Events.Include(e => e.EventType).Include(e => e.Organiser).Where(e => e.Deleted != true); 
            if (User.IsInRole("Organiser"))
            {
                 events = events.Where(e=>e.Organiser.Equals(db.Users.FirstOrDefault(c=>c.Username == User.Identity.Name)));
            }
            
            return View(events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        [Authorize(Roles = "Organiser")]
        public ActionResult Create()
        {
            Event model = new Event()
            {
                OrganiserID = db.Users.FirstOrDefault(c => c.Username == User.Identity.Name).ID,
                Organiser = (Organiser)db.Users.FirstOrDefault(c => c.Username == User.Identity.Name)
            };
            ViewBag.EventTypeID = new SelectList(db.EventTypes, "ID", "Title");
            ViewBag.OrganiserID = new SelectList(db.Users, "ID", "Username");
            return View(model);
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Organiser")]
        public ActionResult Create([Bind(Include = "ID,Name,Description,Created,LastEdit,StartDate,RegistrationStart,RegistrationEnd,Location,Deleted,OrganiserID,EventTypeID,Price")] Event @event)
        {
            Debug.WriteLine(@event.Created);
            Debug.WriteLine(@event.LastEdit);
            @event.Created = DateTime.Now;
            @event.LastEdit = DateTime.Now;
            Debug.WriteLine(@event.Created);
            Debug.WriteLine(@event.LastEdit);
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EventTypeID = new SelectList(db.EventTypes, "ID", "Title", @event.EventTypeID);
            ViewBag.OrganiserID = new SelectList(db.Users, "ID", "Username", @event.OrganiserID);
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = "Organiser")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventTypeID = new SelectList(db.EventTypes, "ID", "Title", @event.EventTypeID);
            ViewBag.OrganiserID = new SelectList(db.Users, "ID", "Username", @event.OrganiserID);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Organiser")]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,Created,LastEdit,StartDate,RegistrationStart,RegistrationEnd,Location,Deleted,OrganiserID,EventTypeID,Price")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EventTypeID = new SelectList(db.EventTypes, "ID", "Title", @event.EventTypeID);
            ViewBag.OrganiserID = new SelectList(db.Users, "ID", "Username", @event.OrganiserID);
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = "Organiser")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [Authorize(Roles = "Organiser")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            @event.Deleted = true;
            //db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Organiser,Admin")]
        public ActionResult Summary()
        {
            var a = db.Users.Include(e => e.Event).Where(e => e.Deleted != true);
            var events=db.Events.Include(e => e.EventType).Include(e => e.Organiser).Where(e => e.Deleted != true);
            if (User.IsInRole ("Admin"))
            {
            var OrganiserID = db.Users.FirstOrDefault(c => c.Username == User.Identity.Name).ID;
                events = events.Where(e => e.OrganiserID == OrganiserID);
            }
            //foreach (Event aea in events){
            //    var all =  aea.Attendees.Count
            //}
            //ViewData["students"] = studentList;

            return View(events.ToList());
        }
        [Authorize(Roles = "Attendee")]
        public ActionResult Register()
        {
            var events = db.Events.Include(e => e.EventType).Include(e => e.Organiser).Where(e => e.Deleted != true);
            return View(events.ToList());
        }
        [HttpPost]
        [Authorize(Roles = "Attendee")]
        public ActionResult Register(int id)
        {
            Debug.WriteLine("----------------");
            Event @event = db.Events.Find(id);
            @event.Attendees.Add ((Attendee)db.Users.FirstOrDefault(c => c.Username == User.Identity.Name));
            //db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Register");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _272ass.Data;
using _272ass.Models;

namespace _272ass.Controllers
{
    public class UsersController : Controller
    {
        private _272assContext db = new _272assContext();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Username,Password,Deleted,CreatedDate,LastEdit")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Username,Password,Deleted,CreatedDate,LastEdit")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Attendee")]
        public ActionResult Registration()
        {
            var events = db.Events.Include(e => e.EventType)
                .Include(e => e.Attendees).Where(e => e.Deleted != true)
                .Where(e => e.Attendees.Any(a => a.Username == User.Identity.Name));
            return View(events.ToList());
        }
        [Authorize(Roles = "Attendee")]
        [HttpPost]
        public ActionResult Registration(int id)
        {
            Debug.WriteLine("-------------");
            Attendee atte = db.Attendees.FirstOrDefault(a => a.Username == User.Identity.Name);
            Event @event = db.Events.Find(id);
            Debug.WriteLine(@event.Attendees.FirstOrDefault(a => a.Username == User.Identity.Name));
            var ea = @event.Attendees.Remove(atte);
            Debug.WriteLine(ea);
            //db.Events.Remove(@event);
            db.SaveChanges();
            
            return RedirectToAction("Registration");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-dark bg-dark container navbar-expand-lg">
            <div class="container-fluid">

                <button type="button" class="navbar-toggler" data-bs-toggle="collapse"
                        data-bs-target="#navcol" aria-controls="navcol"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navcol">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        @{
                            if (User.Identity.IsAuthenticated && !(User.IsInRole("Attendee")))
                            {
                                <li class="nav-item">@Html.ActionLink("Manage Event", "Index", "Events", null, new { @class = "nav-link  align-middle" })</li>
                                if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">@Html.ActionLink("Manage Users", "Index", "Users", null, new { @class = "nav-link  align-middle" })</li>
                                }
                                <li class="nav-item">@Html.ActionLink("Event Summary", "Summary", "Events", null, new { @class = "nav-link  align-middle" })</li>
                                <li class="nav-item d-flex me-auto"></li>
                            }
                            else if (User.Identity.IsAuthenticated)
                            {

                                <li class="nav-item">@Html.ActionLink("Sign Up for Events", "Register", "Events", null, new { @class = "nav-link  align-middle" })</li>
                                <li class="nav-item">@Html.ActionLink("Manage your Events", "Registration", "Users", null, new { @class = "nav-link  align-middle" })</li>
                            }
                        }


                    </ul>
                </div>
                @Html.ActionLink("Main Page", "Index", "Home", new { area = "" }, new { @class = "navbar-brand align-middle" })
                <div class="collapse navbar-collapse" id="navcol">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">@Html.ActionLink("Events", "Index", "Events", new { @class = "nav-link  align-middle" })</li>
                        <li class="nav-item">@Html.ActionLink("About", "About", "Home", new { @class = "nav-link  align-middle" })</li>
                        <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", new { @class = "nav-link  align-middle" })</li>
                        <li class="nav-item d-flex me-auto">
                            @{
                                if (User.Identity.IsAuthenticated)
                                {
                                    @Html.ActionLink("Log Out", "Logout", "Home", null, new { @class = "nav-link align-right" })

                                }
                                else
                                {
                                    @Html.ActionLink("Account", "Login", "Home",null, new { @class = "nav-link align-right" })
                                }
                            }
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </div>

    <div class="container body-content mb-8">
        @RenderBody()
        <div class="position-relative bottom-0 start-20 vw-100 ">
            <hr />
            <footer >
                <p>&copy; @DateTime.Now.Year - KOI - Group 4</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>